apiVersion: argoproj.io/v1alpha1
kind: Application
metadata: 
  name: 
  namespace: argocd
spec: 
  destination: 
    namespace: 
    server: ""
  project: default
  source: 
    path: 
    repoURL: ""
    targetRevision: 
  syncPolicy:
    syncOptions:
      - CreateNamespace=true